use Online_Retail;
##################################################################################################
## "Customers Analysis" ##

select 
   Customer_Value_Segment, 
   Count(CustomerID) as Total_Customers, 
   round(Sum(Estimated_CLV) ,2) as Total_CLV
from rfm_clv_customer
where CustomerID <> 0 
group by Customer_Value_Segment
order by Total_CLV desc;
##########

# who are customers had top revenue? And Net Revenue 

with Orders as (
			select 
				CustomerID,
                Sum(Revenue) as Total_Revenue
			from Fact_Orders
            where CustomerID <> 0
            group by CustomerID )
select 
	O.CustomerID,
    O.Total_Revenue,
    N.Net_Revenue
from Orders O
left join vw_net_revenue_per_customer N
on O.CustomerID = N.CustomerID
order by O.Total_Revenue desc
limit 20 ;

###################################################################################
# Which Segment has Lowest Returns?

with Orders as (
    select CustomerID, sum(Revenue) as Total_Revenue
    from fact_orders
    group by CustomerID
),
Returns_ as (
    select CustomerID, sum(Total_Amount) as Total_Returns
    from fact_returns
    group by CustomerID
)

select 
   A.RFM_Segment,
   Sum( O.Total_Revenue ) as Total_Revenue ,
   Sum(coalesce( R.Total_Returns,0)) as Total_Returns ,
   round( Sum(coalesce( R.Total_Returns,0)) / Sum( O.Total_Revenue ) * 100 ,2) as Return_Rate 
from rfm_clv_customer A 
left join Orders O   on A.CustomerID = O.CustomerID
left join Returns_ R on A.CustomerID = R.CustomerID
where O.CustomerID <> 0
group by A.RFM_Segment ; 

 
###################################################################################
# Percentage of revenue By RFM Segments

with Orders as (
           select 
               CustomerID, Sum(Revenue) as Total_Revenue
			from Fact_Orders
            where CustomerID <> 0
            group by CustomerID )
select 
    RFM.RFM_Segment,
    Sum(O.Total_Revenue) As Total_Revenue,
	round( Sum(O.Total_Revenue)  / (select sum(Total_Revenue) from Orders ) * 100 ,2) as Revenue_Rate
from rfm_clv_customer RFM
left join Orders O
on RFM.CustomerID = O.CustomerID
where RFM.CustomerID <> 0
group by RFM.RFM_Segment ; 

###################################################################################
# Percentage of revenue By Customer Value

with Orders as (
			select 
				CustomerID,
                sum(Revenue) As Total_Revenue
			from Fact_Orders
            where CustomerID <> 0
            group by CustomerID )

select 
    RFM.Customer_Value_Segment,
    Sum(O.Total_Revenue) As total_Revenue,
    round( Sum(O.Total_Revenue) / (select Sum(Total_Revenue) from Orders) * 100 ,2) AS Revenue_Rate
from RFM_CLV_Customer RFM
join Orders O On RFM.CustomerID = O.CustomerID
where RFM.CustomerID <> 0
group by RFM.Customer_Value_Segment
order by Revenue_Rate desc ;


   
###################################################################################
## How much revenue is generated by Repeat Customers vs One-time Customers? \\\ And Repeat vs One-time × Avg Order Value
with Orders as (
			select 
				CustomerID,
                sum(Revenue) As Total_Revenue,
                count(distinct invoice) as Total_Orders,
                case 
                   when count(distinct invoice) > 1 then 'Repeat_Customers'
                   else 'One_Time_Customers'
				End As Customer_Type
			From Fact_Orders
            where CustomerId <> 0
            group by CustomerID )

select
	Customer_Type,
    round( Count(CustomerID) / (select Count(distinct CustomerID) from Fact_Orders where CustomerId <> 0) *100 ,2) As Percentage_Of_Customers,
    sum(Total_Revenue) As Total_Revenue,
    round( Sum(Total_Revenue) / (select Sum(Revenue) from Fact_Orders where CustomerID <> 0 ) *100 ,2) as Revenue_Share_Percentage,
    sum(Total_Orders)  As Total_Orders,
    round( sum(Total_Revenue) / sum(Total_Orders)  ,2) As AOV
from Orders
group by Customer_Type ;


###################################################################################
# RFM Segments By Repeat Customers

with Orders As (
			select 
               CustomerID,
               Sum(Revenue) As Total_Revenue,
               Count(distinct invoice) as Total_Orders,
               case 
                  when Count(distinct Invoice) > 1 then 'Repeat_Customer'
                  else 'One_time_Customer'
			   End As Customer_Type
			From Fact_Orders
            Where CustomerID <> 0
            group by CustomerID )

select 
    RFM.RFM_Segment,
    O.Customer_Type,
    round( count(O.CustomerID) / ( select count(distinct CustomerID ) from Fact_Orders Where CustomerID <> 0 ) *100 ,2) 
    As Percentage_Of_Customers,
    round( sum(O.Total_Revenue) / (select Sum(Revenue) from Fact_Orders Where CustomerID <> 0 ) *100 ,2) 
    As Percentage_Of_Revenue,
    round( sum(O.Total_Revenue) / sum(O.Total_Orders) ,2) As AOV
from RFM_CLV_Customer RFM
join Orders O              On RFM.CustomerID = O.CustomerID
where RFM.CustomerID <> 0
group by RFM.RFM_Segment, O.Customer_Type ;

####################################################          ##############
# Who is New and lost RFM, even though he's a Repeat Customer?  

with Orders As (
			select 
               CustomerID,
               Sum(Revenue) As Total_Revenue,
               Count(distinct invoice) as Total_Orders,
               case 
                  when Count(distinct Invoice) > 1 then 'Repeat_Customer'
                  else 'One_time_Customer'
			   End As Customer_Type
			From Fact_Orders
            Where CustomerID <> 0
            group by CustomerID )

select 
    RFM.CustomerID,
    RFM.RFM_Segment,
    O.Customer_Type,
	sum(O.Total_Revenue) as Total_Revenue,
    sum(O.Total_Orders) as Total_Orders ,
    round( sum(O.Total_Revenue) / sum(O.Total_Orders) ,2) As AOV
from RFM_CLV_Customer RFM
join Orders O              On RFM.CustomerID = O.CustomerID
where RFM.CustomerID <> 0 And RFM.RFM_Segment in ( 'New', 'Lost' ) And  O.Customer_Type = 'Repeat_Customer'
group by RFM.CustomerID ;



#####################################################################################
## Customer Lifecycle Flow  \ How customers move across lifecycle stages quarter-over-quarter?

SELECT
    Prev_Quarter,
    Current_Quarter,
    Transition,
    COUNT(CustomerID) AS Total_Customers,
	ROUND( COUNT(CustomerID) / SUM(COUNT(CustomerID)) OVER (PARTITION BY Current_Quarter) * 100 ,2) AS Percent_of_Quarter
FROM Customer_Lifecycle_Transition
where Prev_Quarter is not null and Transition is not null and Current_Customer_Value <> Prev_Customer_Value
GROUP BY
    Prev_Quarter,
    Current_Quarter,
    Transition
ORDER BY
    Current_Quarter,
    Total_Customers desc;


##################################################################################### 
## CLV vs RFM Mismatch  \\  Are high RFM customers always high CLV customers?

select 
    CustomerID,
    RFM_Segment,
    CLV_Segment
from rfm_clv_customer
where RFM_Segment = 'Vip' ;


# Net Movement Score (Upgrades − Downgrades)
# Early Warning System (مين Regular ومعرّض ينزل)
# Churn Prediction Logic (SQL-based)


    
